trigger:
  batch: 'true'
  branches:
    include:
    - dev
        
pool:
  name: Default

steps:
- task: PowerShell@2
  displayName: Build
  env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    targetType: filePath
    filePath: ./build.ps1
