trigger:
  batch: true
  branches:
    include:
    - dev/*
    - prod/*

pool:
  name: Default
  demands:
  - Agent.ComputerName -equals mskbuild4

steps:
- task: PowerShell@2
  displayName: Pipeline
  inputs:
    targetType: filePath
    filePath: ./_CI/pipeline.ps1
