trigger: 
  batch: true
  branches:
    include:
    - dev/*
    - prod/*

pool:
  name: Default
  demands:
    - EOS_NODEJS

steps:
  - task: PowerShell@2
    displayName: Pipeline
    inputs:
      targetType: filePath
      filePath: ./_CI/pipeline.ps1