export enum AppsettingsParams {
    Email = "Eos.Platform.Settings.Email",
    Converter = "Eos.Platform.Settings.Converter",
    Cryptography = "Eos.Delo.Settings.Cryptography",
    Common = "Eos.Delo.Settings.Common",
    Fdulz = "Eos.Delo.Settings.Fdulz",
    "Search.Indexer" = "Eos.Platform.Settings.Search.Indexer",
    Archivist = "Eos.Delo.Settings.Archivist",
    Sms = "Eos.Platform.Settings.Sms",
    Notification = "Eos.Platform.Settings.Notification",
    ExtendedProtocol = "Eos.Delo.Settings.ExtendedProtocol",
    FileOper = "Eos.Delo.Settings.FileOper",
    Identity = "Eos.Platform.Settings.Identity",
}
export enum AppsettingsTypename {
    TCryptography = "CryptographyCfg",
    TConverter = "ConverterCfg",
    TArchivist = "ArchivistCfg",
    TCommon = "CommonCfg",
    TReceive = "ReceiveCfg",
    TSend = "SendCfg",
    TFiles = "FilesCfg",
    TFdulz = "FdulzCfg",
    TKafka = "KafkaCfg",
    TElastic = "ElasticCfg",
    TNotification = "NotificationCfg",
    TExportStorage = "ExportStorageCfg",
    Preview = "PreviewCfg",
    Session = "SessionCfg"
}
